# Generated by Django 4.1 on 2022-09-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drf',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
